Repository kovacspeter07/CraftIt, pull requests merged in 2025-01, with the labels that each got.

#7 base plan done
  plan/plan.txt
Labels: documentation

#10 5 background changes
  index.html
  short_grass.png
  style.css
  tall_grass_bottom.png
  tall_grass_top.png
Labels: enhancement

#18 bug fix completed
  index.html
Labels: bug
